name: MatrixMultiplication
version: 0.1.0.0
github: "e2e4b6b7/MatrixMultiplication"
license: BSD3
author: "Roman Venediktov"
maintainer: "e2e4b6b7@gmail.com"
copyright: "2021 Roman Venediktov"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/e2e4b6b7/MatrixMultiplication#readme>

dependencies:
  - base >= 4.7 && < 5
  - semirings
  - tasty-hunit

library:
  source-dirs: src

tests:
  MatrixMultiplication-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - MatrixMultiplication
